### ISSUE TITLE
Support for Veeam Backup & Replication V11

### ISSUE THREAD

**Issue by ralfthiel** [falkobanaszak/vCenter-role-for-Veeam#2]
Hi,
thanks for the great script. Would you adopt it to Veeam Backup & Replication V11?
https://helpcenter.veeam.com/docs/backup/permissions/cumulativepermissions.html?ver=110
Thanks again.

**Comment by falkobanaszak** [comment]
Hi,
yes it is on my list to update it to v11.
Did you try it with version 11 and had some issues ?
Thanks !

**Comment by ralfthiel** [comment]
Hi,
I haven't tried it, because I don't have a test environment yet.
I compared the script with the Veeam documentation and I think there is only a minimal difference between them.

**Comment by falkobanaszak** [comment]
HI @ralfthiel 
I just updated the script to the priviliges from Veeam Backup & Replication Version 11.
Have fun :)

**Comment by falkobanaszak** [comment]
Script has been updated to Veeam V11 permissions

**Comment by ralfthiel** [comment]
> HI @ralfthiel
> I just updated the script to the priviliges from Veeam Backup & Replication Version 11.
> Have fun :)

Brilliant, thank you!
Will test it asap.
