### ISSUE TITLE
I don't speak English and I noticed a malfunction. Please fix it when you have time. Thank you.

### ISSUE THREAD

**Issue by z15858167** [falkobanaszak/vCenter-role-for-Veeam#7]
![image](https://github.com/falkobanaszak/vCenter-role-for-Veeam/assets/25273238/7b2c62f2-3dcd-4d93-8a25-4a7dc1467ee9)

VMware-PowerCLI-13.1.0-21624340.zip

**Comment by falkobanaszak** [comment]
Hey, it seems like you do not have VMware PowerCLI installed correctly. This script relies on VMware PowerCLI being installed beforehand.
Kindly check the VMware docs on how to install VMware PowerCLI to your needs: https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.esxi.install.doc/GUID-F02D0C2D-B226-4908-9E5C-2E783D41FE2D.html
